enum ImdStationType {
  dopplerRadar,
  awsObservatory,
  cycloneWarningCentre,
  lightningSensor,
}

class ImdStation {
  final String name;
  final String state;
  final double latitude;
  final double longitude;
  final ImdStationType type;
  final String radarBand; // S-Band, C-Band, X-Band, etc.
  final int rangeKm;
  final String status;
  final double? currentTempC;
  final int? currentAqi;
  final double? currentRainMmH;

  const ImdStation({
    required this.name,
    required this.state,
    required this.latitude,
    required this.longitude,
    required this.type,
    this.radarBand = 'S-Band (Doppler)',
    this.rangeKm = 250,
    this.status = 'Operational 24/7',
    this.currentTempC,
    this.currentAqi,
    this.currentRainMmH,
  });

  static const List<ImdStation> officialStations = [
    // Doppler Weather Radars (DWR)
    ImdStation(
      name: 'Chennai DWR (Port)',
      state: 'Tamil Nadu',
      latitude: 13.0827,
      longitude: 80.2707,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 500,
      currentTempC: 31.2,
      currentAqi: 74,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Mumbai DWR (Veravali/Colaba)',
      state: 'Maharashtra',
      latitude: 18.9220,
      longitude: 72.8347,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 500,
      currentTempC: 30.5,
      currentAqi: 112,
      currentRainMmH: 0.2,
    ),
    ImdStation(
      name: 'Kolkata DWR (Alipore)',
      state: 'West Bengal',
      latitude: 22.5726,
      longitude: 88.3639,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 500,
      currentTempC: 29.8,
      currentAqi: 145,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Delhi DWR (Mausam Bhawan)',
      state: 'Delhi NCR',
      latitude: 28.5900,
      longitude: 77.2200,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 500,
      currentTempC: 28.4,
      currentAqi: 168,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Coimbatore AWS / Agromet',
      state: 'Tamil Nadu',
      latitude: 10.9027,
      longitude: 76.9934,
      type: ImdStationType.awsObservatory,
      radarBand: 'Surface Station',
      rangeKm: 100,
      currentTempC: 26.5,
      currentAqi: 68,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Bengaluru DWR (Peenya)',
      state: 'Karnataka',
      latitude: 13.0285,
      longitude: 77.5197,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 25.1,
      currentAqi: 58,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Hyderabad DWR (Begumpet)',
      state: 'Telangana',
      latitude: 17.4531,
      longitude: 78.4677,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 28.9,
      currentAqi: 92,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Thiruvananthapuram DWR',
      state: 'Kerala',
      latitude: 8.5241,
      longitude: 76.9366,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 29.0,
      currentAqi: 45,
      currentRainMmH: 1.2,
    ),
    ImdStation(
      name: 'Kochi DWR',
      state: 'Kerala',
      latitude: 9.9312,
      longitude: 76.2673,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 29.4,
      currentAqi: 52,
      currentRainMmH: 0.6,
    ),
    ImdStation(
      name: 'Goa DWR (Panaji)',
      state: 'Goa',
      latitude: 15.4909,
      longitude: 73.8278,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 30.1,
      currentAqi: 48,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Visakhapatnam DWR',
      state: 'Andhra Pradesh',
      latitude: 17.6868,
      longitude: 83.2185,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR (Cyclone Warning)',
      rangeKm: 500,
      currentTempC: 30.8,
      currentAqi: 82,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Machilipatnam DWR',
      state: 'Andhra Pradesh',
      latitude: 16.1800,
      longitude: 81.1300,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 500,
      currentTempC: 31.0,
      currentAqi: 75,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Paradip DWR',
      state: 'Odisha',
      latitude: 20.2600,
      longitude: 86.6700,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 500,
      currentTempC: 29.2,
      currentAqi: 88,
      currentRainMmH: 0.4,
    ),
    ImdStation(
      name: 'Gopalpur DWR',
      state: 'Odisha',
      latitude: 19.2600,
      longitude: 84.9000,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 500,
      currentTempC: 29.7,
      currentAqi: 79,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Jaipur DWR',
      state: 'Rajasthan',
      latitude: 26.9124,
      longitude: 75.7873,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 33.1,
      currentAqi: 135,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Srinagar DWR',
      state: 'Jammu & Kashmir',
      latitude: 34.0837,
      longitude: 74.7973,
      type: ImdStationType.dopplerRadar,
      radarBand: 'X-Band DWR',
      rangeKm: 150,
      currentTempC: 17.2,
      currentAqi: 42,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Cherrapunji DWR (Sohra)',
      state: 'Meghalaya',
      latitude: 25.2700,
      longitude: 91.7300,
      type: ImdStationType.dopplerRadar,
      radarBand: 'S-Band DWR',
      rangeKm: 250,
      currentTempC: 20.4,
      currentAqi: 35,
      currentRainMmH: 4.8,
    ),
    ImdStation(
      name: 'Agartala DWR',
      state: 'Tripura',
      latitude: 23.8315,
      longitude: 91.2868,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 28.6,
      currentAqi: 62,
      currentRainMmH: 0.0,
    ),
    ImdStation(
      name: 'Mohanbari DWR (Dibrugarh)',
      state: 'Assam',
      latitude: 27.4800,
      longitude: 95.0200,
      type: ImdStationType.dopplerRadar,
      radarBand: 'C-Band DWR',
      rangeKm: 250,
      currentTempC: 27.5,
      currentAqi: 50,
      currentRainMmH: 0.0,
    ),
  ];
}
